# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d4c5ffc1a040e58a4b76d07f04df96ffcf46f4780e57de04ea0229c16b93f06f341d62206ea2858b1c4e87b5aba2dc476b9ad18c223de19f8eee214c746c6d9

test:
  secret_key_base: 287d2748ea89f2774cdd643888e124e31631a921d6c40dc330402904dd451ae6563b87296415df9bd0beb3c834dd5d1fa6c63bedb2520956657753824d0f8996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
